In [6]:
import torch

x=torch.tensor(6.7)
y=torch.tensor(0.0)

w=torch.tensor(1.0, requires_grad=True)
b=torch.tensor(0.0, requires_grad=True)

In [7]:
def loss(prediction,target):
  epsilon = 1e-8
  prediction = torch.clamp(prediction,epsilon,1-epsilon)
  return -target*torch.log(prediction)-(1-target)*torch.log(1-prediction)

In [8]:
z = w*x + b
y_pred = torch.sigmoid(z)

loss = loss(y_pred,y)

In [9]:
loss.backward()

In [10]:
w.grad

tensor(6.6918)

In [11]:
b.grad

tensor(0.9988)

In [34]:
x = torch.tensor([1.0,2.0,3.0], requires_grad=True)
y = (x**2).mean()

In [35]:
y.backward()
x.grad


tensor([0.6667, 1.3333, 2.0000])

In [32]:
x.grad.zero_()

tensor([0., 0., 0.])

In [31]:
x.requires_grad_(False)

tensor([1., 2., 3.])