In [1]:
import torch
import torch.nn as nn

In [2]:
class NeuralNetwork(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        out = self.linear(features) 
        out = self.sigmoid(out)
        return out   

In [3]:
features = torch.rand(10,5)

model = NeuralNetwork(features.shape[1])
model(features)

tensor([[0.4753],
        [0.4657],
        [0.4415],
        [0.4083],
        [0.4132],
        [0.4499],
        [0.4341],
        [0.4415],
        [0.4435],
        [0.4696]], grad_fn=<SigmoidBackward0>)

In [5]:
model.linear.weight

Parameter containing:
tensor([[-0.2243,  0.2254, -0.2879, -0.0981,  0.0179]], requires_grad=True)

In [7]:
model.linear.bias

Parameter containing:
tensor([-0.0245], requires_grad=True)

In [9]:
from torchinfo import summary
summary(model, input_size=(1, features.shape[1]))

Layer (type:depth-idx)                   Output Shape              Param #
NeuralNetwork                            [1, 1]                    --
├─Linear: 1-1                            [1, 1]                    6
├─Sigmoid: 1-2                           [1, 1]                    --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00