In [3]:
import torch
print(torch.__version__)
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))
else:
  print("Not avilable")

2.6.0+cu124
Not avilable


# Creating a Tensor

In [6]:
a=torch.empty(2,3)

In [7]:
type(a)

torch.Tensor

In [9]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.rand(2,3)

tensor([[0.6885, 0.2501, 0.5430],
        [0.9834, 0.9012, 0.4611]])

In [14]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [19]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [20]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [22]:
torch.full((2,3),5)

tensor([[5, 5, 5],
        [5, 5, 5]])

# Tensor Shapes

In [23]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [24]:
torch.empty_like(x)

tensor([[    135193280028048,     135193280028048,                   0],
        [                  0,                   0, 7310593858020254331]])

In [25]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

# Data Types

In [26]:
x.dtype

torch.int64

In [29]:
torch.tensor([1.9,2.0,3.0], dtype=torch.int64)

tensor([1, 2, 3])

In [31]:
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

# Mathematica Opeartion

In [34]:
x+2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [33]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [35]:
x*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [36]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [38]:
y=torch.tensor([[1,2,3],[4,5,6]])

In [39]:
x*y

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [40]:
x**y

tensor([[    1,     4,    27],
        [  256,  3125, 46656]])

In [41]:
torch.abs(x)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [42]:
torch.sum(x)

tensor(21)

In [43]:
torch.sum(x,dim=1) #2nd row

tensor([ 6, 15])

# Matrix Opeartion

In [49]:
torch.matmul(x,torch.inverse(x))

RuntimeError: linalg.inv: A must be batches of square matrices, but they are 2 by 3 matrices

In [46]:
torch.dot(x,y)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [50]:
x>y

tensor([[False, False, False],
        [False, False, False]])

In [52]:
torch.log(x)

tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])

In [53]:
torch.sqrt(x)

tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])

# Inplace Operations

In [54]:
x.add_(y)

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [55]:
x

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [56]:
y

tensor([[1, 2, 3],
        [4, 5, 6]])

# Copying a Tensor

In [60]:
id(x)

135188876949072

In [61]:
id(y)

135188873737904

In [62]:
z=x.clone()

In [64]:
id(z)

135188873151888