In [3]:
import torch
print(torch.__version__)
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))
    device = torch.device("cuda")
else:
  print("Not avilable")

2.6.0+cu124
Tesla T4


# Creating Tensor in GPU

In [4]:
torch.rand((2,3),device=device)

tensor([[0.6973, 0.5959, 0.4678],
        [0.9796, 0.9129, 0.9055]], device='cuda:0')

In [6]:
a = torch.rand(2,3)
a

tensor([[0.4364, 0.6166, 0.8645],
        [0.3733, 0.5678, 0.8752]])

In [8]:
b = a.to(device)

In [9]:
b+5

tensor([[5.4364, 5.6166, 5.8645],
        [5.3733, 5.5678, 5.8752]], device='cuda:0')

# Creating difference between CPU vs GPU

In [11]:
import time

# Set matrix size
size = 1000

# Create two random matrices on CPU
matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

# -------- CPU Timing --------
start_cpu = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
end_cpu = time.time()
cpu_time = end_cpu - start_cpu
print(f"CPU time: {cpu_time:.4f} seconds")

# -------- GPU Timing (if available) --------
if torch.cuda.is_available():
    device = torch.device("cuda")

    # Move matrices to GPU
    matrix_gpu1 = matrix_cpu1.to(device)
    matrix_gpu2 = matrix_cpu2.to(device)

    # Warm-up GPU (optional but helps accurate timing)
    torch.matmul(matrix_gpu1, matrix_gpu2)

    # Synchronize before starting timing
    torch.cuda.synchronize()
    start_gpu = time.time()

    result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)

    # Synchronize again to get accurate end time
    torch.cuda.synchronize()
    end_gpu = time.time()
    gpu_time = end_gpu - start_gpu

    print(f"GPU time: {gpu_time:.4f} seconds")
else:
    print("CUDA GPU is not available.")



CPU time: 0.0285 seconds
GPU time: 0.0008 seconds


# Reshapping Tensors

In [12]:
a = torch.ones(4,4)

In [13]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])